language: node_js
node_js:
  - 12.18.3
cache: npm


install:
  - npm install

script:
  - npm test
  - CI=false npm run build


deploy:
  provider: firebase
  skip-cleanup: true
  token: $FIREBASE_TOKEN
  local_dir: build
