language: node_js
node_js:
  - 12.18.3
cache: npm

script:
  - npm test
  - CI=false npm run build

install:
  - npm install -g firebase-tools


after_success:
  - firebase deploy --token $FIREBASE_TOKEN
